Feat/controller history
MTES-MCT/mobilic-api pull request #100
Opened 2022-08-19 14:10 UTC by tristan-gueguen

2022-08-22 14:36 UTC, sandrica89 commented on app/models/controller_control.py
> +    vehicle_registration_number = db.Column(db.TEXT, nullable=True)
:green_circle:  Je pense que tu peux utiliser un String ici avec une taille restreinte (comme pour `company_name` car l'immatriculation d'un véhicule n'est jamais très longue.

2022-08-22 14:37 UTC, sandrica89 commented on app/data_access/control.py
> +class ControllerControlOutput(BaseSQLAlchemyObjectType):
:orange_circle: Adapter avec les changements d'une autre PR en cours : https://github.com/MTES-MCT/mobilic-api/pull/101/files#diff-047bec21b9194672f5739b2d0c8b94e3d324bd7608fe9fa80942416a4d60a85a

2022-08-29 09:48 UTC, tristan-gueguen commented on app/models/controller_control.py
> +    vehicle_registration_number = db.Column(db.TEXT, nullable=True)
Je me suis dit que le mieux était de m'aligner sur le type de colonne de `registration_number` de `Vehicle` puisqu'il est possible que dans certains cas on recopie ce champ dans celui-ci

2022-09-02 10:05 UTC, rtaieb requested changes

2022-09-02 10:05 UTC, rtaieb commented on app/data_access/controller_user.py
> +    @user_resolver_with_consultation_scope(
:orange_circle: Je ne vois pas à quoi sert cette habilitation ici, et quel appel elle peut filtrer. Et je ne pense pas que le paramètre consultation_scope soit utile pour la méthode resolve_controls()

2022-09-05 08:16 UTC, sandrica89 commented on app/data_access/controller_user.py
> +    @user_resolver_with_consultation_scope(
Ca fait effectivement partie des points d'intérrogation qu'on avait et qu'on voulait voir avec toi. Cela ne semblait pas fonctionner sans ça.
Note pour plus tard : quand on fait une pair review, il faudrait quand même qu'on note nos remarques pour garder une trace des échanges :)

2022-09-05 11:59 UTC, tristan-gueguen commented on app/models/controller_control.py
> +                a
2. A priori cette requete existait bien, je l'ai utilise a la place

2022-09-06 15:00 UTC, merged