Allow to use new employment token and restrict to associated company
MTES-MCT/mobilic-api pull request #156
Opened 2023-01-16 08:33 UTC by rtaieb

https://trello.com/c/xDhAr5cK/899-gestion-des-appels-avec-les-token-oauth

2023-01-16 12:35 UTC, sandrica89 reviewed
Pour info, je n'ai pas vérifié lors de la review si tout fonctionnait et si certains endroits avaient pu être oublié. On s'en rendra compte avec la tache de tests de tous les endpoints qui peuvent être appelés par un client.

2023-01-16 12:35 UTC, sandrica89 commented on app/helpers/authorization.py
> +                )
:green_circle: 
```suggestion
            check_company_id_against_scope(company_id)
```

2023-01-16 12:35 UTC, sandrica89 commented on app/helpers/authentication.py
> +    if not matching_token:
:green_circle: On pourrait sortir cette logique dans une fonction `check_matching_token_client_id` pour avoir le même niveau d'abstraction que `check_protected_client_id_company_id`

2023-01-16 12:35 UTC, sandrica89 commented on app/controllers/third_party_employment.py
> +            existing_link.employment.validation_time = datetime.now()
:green_circle: On pourrait sortir cette logique dans 2 fonctions `activate_user` et `validate_employment` pour garder le même niveau d'abstraction que `generate_employment_token`

2023-01-16 12:35 UTC, sandrica89 commented on app/controllers/mission.py
> +    @check_company_against_scope_wrapper(
:orange_circle: Pourquoi avoir fait un decorator spécifique et ne pas l'avoir intégrer dans `with_authorization_policy` ? Est-ce parce que ce dernier est déjà trop complexe ou y a-t-il une autre raison ?

2023-01-16 12:35 UTC, sandrica89 commented on app/helpers/authentication.py
> +        raise AuthenticationError("Company token has been revoked")
:clap: d'avoir pensé à ce cas ! 

Mais du coup je me demande s'il ne faudrait pas faire ce check quand un client query un employment token dans `app/controllers/third_party_employment.py` > `resolve_employment_token` :thinking:

2023-01-16 12:35 UTC, sandrica89 commented on app/domain/permissions.py
> +            elif company_further_scoping:
:orange_circle: Aucune chane qu'il y ait à la fois `g.get("company")` et `company_further_scoping` ?

2023-01-16 12:35 UTC, sandrica89 commented on app/helpers/authentication.py
> +    token = request.headers.get("X-EMPLOYMENT-TOKEN")
:green_circle: On pourrait utiliser définir ces valeurs de header dans un fichier dédié (avec "X-API-KEY")

2023-01-16 16:42 UTC, rtaieb commented on app/controllers/mission.py
> +    @check_company_against_scope_wrapper(
parceque je check une règle bien spécifique, et donc ça serait revenu à mettre un deuxième @with_authorization_policy avec juste la nouvelle règle, et donc on aurait relancé toute les méthodes du decorator actuelle. Sinon il aurait fallu l'adapter et comme tu dis je le trouve déjà bien complexe...

2023-01-16 16:48 UTC, rtaieb commented on app/helpers/authentication.py
> +        raise AuthenticationError("Company token has been revoked")
oui, je vais le rajouter

2023-01-16 17:01 UTC, rtaieb commented on app/domain/permissions.py
> +            elif company_further_scoping:
s'il y a les deux et qu'ils sont différents ça sortira déjà en Authentication error à partir de l'appel is_employed_by_company_over_period

2023-01-17 14:34 UTC, sandrica89 requested changes

2023-01-17 14:34 UTC, sandrica89 commented on app/controllers/third_party_employment.py
> +        ):
:orange_circle: Cela risque de renvoyer une erreur si le client_employment_link n'existe pas : 
```suggestion
        if client_employment_link and not check_protected_client_id_company_id(
            client_employment_link.employment.company_id
        ):
```

2023-01-17 15:23 UTC, sandrica89 approved these changes
Arf désolée j'ai fait la suggestion directement sur github donc il n'y a pas eu le reformat de black :/ 
Une fois que ça build c'est good pour moi !

2023-01-17 16:09 UTC, merged