Feat/control bulletin step1
MTES-MCT/mobilic-api pull request #208
Opened 2023-05-03 13:45 UTC by rtaieb

https://trello.com/c/52bKAzh2/1077-bdc-%C3%A9tape-1

https://github.com/MTES-MCT/mobilic/pull/344

2023-05-05 08:22 UTC, tristan-gueguen requested changes

2023-05-05 10:00 UTC, rtaieb commented on app/controllers/controller.py
> +        control_id = graphene.Int(required=False)
Si on fait ça il me semble qu'on perd de vue côtés front les champs qui doivent être envoyés (comme pour BulkActivityItem, qui masque dans apiQueries.js les champs qui sont attendus).
Quels seraient les avantages?

2023-05-05 10:01 UTC, rtaieb commented on app/data_access/control_data.py
> +    # control_bulletin = graphene.Field(ControlBulletinOutput, required=False)
Je vais plutôt supprimer cette ligne qui ne sert à rien

2023-05-17 13:18 UTC, tristan-gueguen approved these changes

2023-06-14 08:37 UTC, merged