Feat/control bulletin export pdf
MTES-MCT/mobilic-api pull request #215
Opened 2023-05-25 08:05 UTC by tristan-gueguen

https://trello.com/c/Kisy8WNb/1080-bdc-g%C3%A9n%C3%A9ration-et-t%C3%A9l%C3%A9chargement

2023-05-25 15:46 UTC, sandrica89 requested changes

2023-05-25 15:46 UTC, sandrica89 commented on app/templates/control_bulletin.html
> +                    <p class="subtitle" style="padding-bottom: 16px;">D.R.E.A.L. DEPARTEMENT</p>
:orange_circle: Cette info doit être dynamique, je pense qu'il s'agit de la valeur "organizational_unit" qui se trouve dans "agent_connect_infos" dans la table "controller_user"

2023-05-25 15:46 UTC, sandrica89 commented on app/helpers/pdf/control_bulletin.py
> +        control_date=control_bulletin.creation_time.strftime("%d/%m/%Y"),
:green_circle: Il me semble que tu peux appliquer le formattage directement dans le template (avec un |). C'est mieux de garder au même endroit tout ce qui est lié à l'affichage, et de ne garder ici que les données brutes (comme ça si ça change, on ne le change que dans le template).

2023-05-26 09:00 UTC, tristan-gueguen commented on app/templates/control_bulletin.html
> +                            <td class="frame-item-left primary-color">N° de bulletin de contrôle:</td>
ah bon ??

2023-05-30 12:16 UTC, sandrica89 approved these changes

2023-06-02 07:55 UTC, merged