Feat/hide employee email
MTES-MCT/mobilic-api pull request #300
Opened 2023-10-25 14:17 UTC by tristan-gueguen

https://trello.com/c/18CqYk0T/944-opt-in-salari%C3%A9-partage-mail-perso-avec-employeur

2023-11-02 17:16 UTC, sandrica89 requested changes

2023-11-02 17:16 UTC, sandrica89 commented on app/models/employment.py
> +    hide_email = db.Column(db.Boolean, nullable=True, default=False)
:orange_circle: Il faudrait l'ajouter dans l'`EmploymentFactory` du seed

2023-11-03 08:49 UTC, tristan-gueguen commented on app/controllers/employment.py
> +                hide_email=user_id is not None,
Marie proposait que l'on mette False tout le temps, sauf si l'employé est invité par Id (et non par email)

2023-11-03 08:49 UTC, tristan-gueguen commented on app/data_access/employment.py
> +            return get_user_with_hidden_email(self.user)
Le resolver renvoie None par defaut

2023-11-03 08:50 UTC, tristan-gueguen commented on app/models/employment.py
> +    hide_email = db.Column(db.Boolean, nullable=True, default=False)
Exact

2023-11-03 09:07 UTC, sandrica89 commented on app/data_access/employment.py
> +            return get_user_with_hidden_email(self.user)
:o Merci pour l'info :)

2023-11-03 09:47 UTC, tristan-gueguen commented on app/controllers/employment.py
> +                hide_email=user_id is not None,
Ah exact je n'avais pas pensé à ça. Donc on effectuerait ca pour tous les employments approved, qui possede un invite token et ou l'email n'est pas renseigne ?

2023-11-03 09:51 UTC, sandrica89 commented on app/controllers/employment.py
> +                hide_email=user_id is not None,
Pourquoi uniquement les approved ? j'aurai dit tout ceux avec invite token et pas d'email

2023-11-03 14:01 UTC, tristan-gueguen commented on app/models/employment.py
> +    hide_email = db.Column(db.Boolean, nullable=True, default=False)
Nullable=False, migration modifiee

2023-11-06 11:25 UTC, sandrica89 approved these changes

2023-11-06 11:28 UTC, merged