feat(controller): improve login error message
MTES-MCT/mobilic-api pull request #357
Opened 2024-03-06 20:47 UTC by gaspard-lonchampt

https://trello.com/c/HrM0rWfG/1376-modifier-le-message-derreur-lors-de-la-cr%C3%A9ation-dun-compte-contr%C3%B4leur-via-mcp

2024-03-12 10:32 UTC, sandrica89 requested changes

2024-03-12 10:32 UTC, sandrica89 commented on app/domain/controller.py
> +        raise AgentConnectAuthenticationError(app.logger.exception(e))
:orange_circle: Cette erreur est utilisée pour les erreurs d'authentification à Agent Connect (typiquement une erreur de token). Est-ce pertinent de l'utiliser ici ? :thinking: L'authent' AC a réussi si on arrive jusqu'ici, ne devrait-on pas utiliser une autre erreur par exemple `AgentConnectForbiddenError` ?

2024-03-12 10:32 UTC, sandrica89 commented on app/domain/controller.py
> +    except Exception as e:
:orange_circle: Je me demande s'il n'est pas préférable de vérifier que `ac_info.get("organizational_unit")` n'est pas null en amont et raise l'erreur dans ce cas. Ici, avec le `try catch` qui englobe la création, on pourrait catch d'autres erreurs, ne pas les voir et donc renvoyer un message d'erreur inadapté.

EDIT après test : :red_circle: Cela ne fonctionne pas, la contrainte en base est levée lors du commit (donc ici avec le `db.session.flush()` et pas avec la ligne dans le `try catch`.

2024-03-14 15:07 UTC, gaspard-lonchampt commented on app/domain/controller.py
> +        raise AgentConnectAuthenticationError(app.logger.exception(e))
Il y a la PR côté front qui avec pour le message d'erreur : https://github.com/MTES-MCT/mobilic/pull/487

2024-04-09 19:24 UTC, sandrica89 commented on app/domain/controller.py
> +    print("---------------------------------------")
:orange_circle: C'est un oubli pour debug ou c'est souhaité que ça parte en recette ou prod avec ?

2024-04-16 11:47 UTC, gaspard-lonchampt commented on app/domain/controller.py
> +    print("---------------------------------------")
C'est clairement un oubli, merci !

2024-04-16 12:02 UTC, sandrica89 approved these changes

2024-04-18 09:05 UTC, merged